name: SBOM Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sbom-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Syft
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh

      - name: Generate SBOM
        run: |
          syft dir:. -o cyclonedx-json > sbom.json
        continue-on-error: false

      # Step 3: Validate SBOM with CycloneDX CLI
      - name: Install CycloneDX CLI
        run: npm install -g @cyclonedx/cyclonedx-cli

      - name: Validate SBOM
        run: |
          cyclonedx-cli validate --input-file sbom.json

      # Step 4: Scan SBOM for vulnerabilities using Grype
      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh

      - name: Vulnerability Scan with Grype
        run: |
          grype sbom:sbom.json -o table

      # Step 5: Snyk Vulnerability and License Scanning
      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth

      - name: Snyk Test
        run: snyk test

      # Step 6: Upload SBOM as an artifact
      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json
